[backdrop]
blur_intensity = 0.99999997764825821
enabled = true
tint_intensity = 0.73999998345971107

[bar]
order = [ "main" ]

    [bar.main]
    background_opacity = 0.0
    capsule = true
    capsule_border = "surface_variant"
    capsule_fill = "surface_variant"
    capsule_foreground = "on_surface_variant"
    capsule_padding = 10.0
    capsule_radius = 6
    capsule_thickness = 0.79999998584389687
    center = [ "group:g4" ]
    color = "primary"
    concave_edge_corners = false
    contact_shadow = false
    end = [ "group:g3", "tray", "group:g1", "session" ]
    font_weight = 700
    icon_color = "primary"
    margin_edge = 6
    margin_ends = 0
    padding = 14
    panel_overlap = 0
    position = "top"
    radius = 0
    radius_top_left = 0
    radius_top_right = 0
    reserve_space = true
    scale = 1.0500000081956387
    shadow = false
    start = [ "group:g2" ]
    thickness = 34
    widget_spacing = 12

        [[bar.main.capsule_group]]
        accordion = false
        accordion_direction = "end"
        border = ""
        enabled = true
        fill = "surface_variant"
        foreground = "primary"
        id = "g2"
        members = [ "workspaces", "active_window" ]
        opacity = 1.0
        padding = 10.0

        [[bar.main.capsule_group]]
        accordion = false
        accordion_direction = "end"
        border = ""
        enabled = true
        fill = "surface_variant"
        foreground = "primary"
        id = "g1"
        members = [ "notifications", "clipboard", "volume" ]
        opacity = 1.0
        padding = 10.0

        [[bar.main.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        foreground = "primary"
        id = "g3"
        members = [ "audio_visualizer", "media" ]
        opacity = 1.0
        padding = 10.0
        radius = 6.0

        [[bar.main.capsule_group]]
        accordion = false
        accordion_direction = "end"
        border = ""
        enabled = true
        fill = "surface_variant"
        foreground = "primary"
        id = "g4"
        members = [ "clock", "weather" ]
        opacity = 1.0
        padding = 10.0
        radius = 6.0

[control_center]
hidden_tabs = [ "power" ]
show_shortcut_labels = false
sidebar = "full"
sidebar_section = "none"

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "dark_mode"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
background_opacity = 0.099999997764825821
enabled = false
icon_size = 34
launcher_icon = "grain"
launcher_position = "end"
position = "left"
radius = 8
show_instance_count = false

[idle]
behavior_order = [ "lock", "idle-behavior" ]

    [idle.behavior.idle-behavior]
    action = "suspend"
    enabled = true
    lock_before_suspend = false
    timeout = 1200.0

    [idle.behavior.lock]
    action = "screen_off"
    enabled = true
    timeout = 300.0

[location]
auto_locate = true

[lockscreen]
blur_intensity = 0.99999997764825821
blurred_desktop = true
enabled = true
tint_intensity = 0.25

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1258.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
background_opacity = 0.93999999999999995
enable_daemon = true
offset_x = 20
offset_y = 12

[osd]
background_opacity = 0.99999997764825821
offset_x = 20
offset_y = 12
position = "top_center"

[shell]
avatar_path = "/home/cbrst/.face.png"
button_borders = false
card_borders = false
clipboard_enabled = true
clipboard_keep_from_closed_apps = true
corner_radius_scale = 1.25
date_format = "%A, %x"
font_family = "0xProto"
input_borders = false
panel_anchor_bar = "main"
popup_borders = false
screen_time_enabled = true
telemetry_enabled = false
time_format = "{:%H:%M}"

    [shell.animation]
    enabled = true
    speed = 1.45

    [shell.launcher]
    categories = true
    compact = false
    show_app_actions = true
    show_icons = true
    sort_by_usage = true

    [shell.panel]
    borders = false
    clipboard_placement = "floating"
    clipboard_position = "top_right"
    control_center_placement = "floating"
    launcher_placement = "floating"
    launcher_position = "center"
    open_near_click_control_center = true
    open_near_click_session = true
    open_near_click_wallpaper = true
    polkit_position = "top_right"
    session_placement = "floating"
    shadow = true
    transparency_mode = "solid"
    wallpaper_placement = "floating"

    [shell.screen_corners]
    enabled = false
    size = 12

    [shell.session]
    show_shortcuts = false

    [shell.shadow]
    alpha = 0.47999999999999998
    direction = "down"

[theme]
builtin = "Ayu"
community_palette = "Monochrome"
custom_palette = "palette"
mode = "dark"
pure_black_dark = false
source = "custom"

    [theme.templates]
    builtin_ids = [ "niri" ]

[wallpaper]
directory = "~/Pictures/Wallpapers"
enabled = true
fill_mode = "crop"
transition = [ "fade", "zoom" ]
transition_duration = 400
transition_on_startup = true

    [wallpaper.automation]
    enabled = false

    [wallpaper.default]
    path = "/home/cbrst/Pictures/Wallpapers/wallpaper.jpg"

    [wallpaper.last]
    path = "/home/cbrst/Pictures/Wallpapers/wallpaper.jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/cbrst/Pictures/Wallpapers/wallpaper.jpg"

[widget.active_window]
display = "text_only"
font_weight = 700
icon_size = 38

[widget.audio_visualizer]
bands = 8
color_1 = "on_tertiary"
color_2 = "error"
mirrored = false
scale = 0.80000000000000004
width = 24

[widget.clock]
font_weight = 700

    [widget.clock.actions]
    left = "panel-toggle control-center"

[widget.media]
artist_first = true
capsule = true
capsule_fill = "on_surface_variant"
capsule_opacity = 0.10000000000000001
capsule_padding = 8
font_weight = 700
hide_album_art = true
hide_when_no_media = true
max_length = 602
title_scroll = "on_hover"

[widget.taskbar]
only_active_workspace = true

[widget.tray]
detached_panel = true
drawer = true

[widget.weather]
font_weight = 700
show_condition = false

[widget.workspaces]
active_pill_size = 2.0
change_color_on_hover = false
empty_color = "tertiary"
focused_color = "primary"
inactive_pill_size = 1.0
label_source = "name"
max_label_chars = 20
occupied_color = "secondary"
pill_scale = 0.59999999999999998
show_labels = false
style = "regular"
