;;; search.el --- Minibuffer pickers -*- lexical-binding: t; -*-
(require 'vertico)
(require 'orderless)
(require 'marginalia)
(require 'consult)
(require 'embark)
(require 'embark-consult)
(vertico-mode 1)
(marginalia-mode 1)
(setq completion-styles '(orderless basic)
      completion-category-defaults nil
      completion-category-overrides '((file (styles partial-completion)))
      consult-project-function (lambda (_) (config-project-root))
      xref-show-xrefs-function #'consult-xref
      xref-show-definitions-function #'consult-xref)
(keymap-set minibuffer-local-map "C-." #'embark-act)
(defun config-find-files (&optional root)
  "Find files under ROOT, or the current directory, honoring ignore rules."
  (interactive)
  (let* ((root (or root default-directory))
         (files (mapcar (lambda (file) (file-relative-name file root))
                        (project-files (cons 'config-project root)))))
    (find-file (expand-file-name (completing-read "File: " files nil t) root))))
(defun config-project-files ()
  (interactive) (config-find-files (config-project-root)))
(defun config-search-project ()
  (interactive) (consult-ripgrep (config-project-root)))
(defun config-search-word ()
  (interactive) (consult-ripgrep (config-project-root) (thing-at-point 'symbol t)))
(defun config-search-open-buffers ()
  (interactive) (consult-line-multi t))
(config-bind "." #'config-find-files)
(config-bind "f f" #'config-find-files)
(config-bind "f r" #'consult-recent-file)
(config-bind "f p" (lambda () (interactive) (config-find-files config-directory)))
(config-bind "," #'consult-buffer)
(config-bind "b b" #'consult-buffer)
(config-bind "SPC" #'config-project-files)
(config-bind "/" #'config-search-project)
(config-bind "*" #'config-search-word)
(config-bind "'" #'vertico-repeat)
(require 'vertico-repeat)
(add-hook 'minibuffer-setup-hook #'vertico-repeat-save)
(config-bind "s t" #'execute-extended-command)
(config-bind "s b" #'consult-line)
(config-bind "s s" #'consult-line)
(config-bind "s B" #'config-search-open-buffers)
(config-bind "h h" #'apropos-command)
(config-bind "h b b" #'embark-bindings)
