;;; vcs.el --- Git hunks and cached asynchronous Git/jj identity -*- lexical-binding: t; -*-
(require 'diff-hl)
(require 'diff-hl-show-hunk)
(require 'magit)
(require 'blamer)
(global-diff-hl-mode 1)
(unless (display-graphic-p)
  (require 'diff-hl-margin)
  (diff-hl-margin-mode 1))
(add-hook 'magit-pre-refresh-hook #'diff-hl-magit-pre-refresh)
(add-hook 'magit-post-refresh-hook #'diff-hl-magit-post-refresh)
(defvar config-vcs-cache (make-hash-table :test #'equal))
(defvar-local config-vcs-repository nil)
(defun config-vcs-diff-counts (diff)
  "Return added, changed and removed line counts from a zero-context DIFF."
  (let ((start 0) (added 0) (changed 0) (removed 0))
    (while (string-match "^@@ -[0-9]+\\(?:,\\([0-9]+\\)\\)? +[+][0-9]+\\(?:,\\([0-9]+\\)\\)? @@" diff start)
      (let* ((old (if (match-string 1 diff) (string-to-number (match-string 1 diff)) 1))
             (new (if (match-string 2 diff) (string-to-number (match-string 2 diff)) 1))
             (common (min old new)))
        (cl-incf added (- new common))
        (cl-incf removed (- old common))
        (cl-incf changed common))
      (setq start (match-end 0)))
    (list added changed removed)))
(defun config-vcs-refresh (&rest _)
  "Refresh repository state without spawning processes during redisplay."
  (setq config-vcs-repository (config-repository))
  (when-let* ((repo config-vcs-repository))
    (unless (plist-get (gethash repo config-vcs-cache) :busy)
      (let* ((default-directory (cdr repo))
             (jj (eq (car repo) 'jj))
             (buffer (generate-new-buffer " *editor-vcs*"))
             (previous (gethash repo config-vcs-cache)))
        (puthash repo (plist-put previous :busy t) config-vcs-cache)
        (make-process
         :name "editor-vcs" :buffer buffer :noquery t :connection-type 'pipe
         :command (if jj
                      '("jj" "log" "-r" "@" "--no-graph" "--color" "never" "-T"
                        "local_bookmarks.map(|b| b.name()).join(\",\") ++ \"@\" ++ change_id.shortest(8) ++ \"\\n\" ++ diff.git(0)")
                    '("git" "diff" "--no-ext-diff" "--no-color" "--unified=0" "--"))
         :sentinel
         (lambda (process _event)
           (when (memq (process-status process) '(exit signal))
             (unwind-protect
                 (if (= (process-exit-status process) 0)
                     (let* ((output (with-current-buffer buffer (buffer-string)))
                            (identity (if jj (car (split-string output "\n")) "Git"))
                            (counts (config-vcs-diff-counts output)))
                       (puthash repo (list :text (apply #'format
                                                       "%s +%d ~%d -%d" identity counts))
                                config-vcs-cache))
                   (puthash repo (list :text "VCS unavailable") config-vcs-cache))
               (kill-buffer buffer)
               (force-mode-line-update t)))))))))
(add-hook 'find-file-hook #'config-vcs-refresh)
(add-hook 'after-save-hook #'config-vcs-refresh)
(add-hook 'buffer-list-update-hook
          (lambda ()
            (unless (equal config-vcs-repository (config-repository))
              (config-vcs-refresh))))
(add-hook 'magit-post-refresh-hook #'config-vcs-refresh)
(add-hook 'focus-in-hook #'config-vcs-refresh)
(add-hook 'window-selection-change-functions #'config-vcs-refresh)
(add-hook 'eat-exit-hook #'config-vcs-refresh)
(defun config-git-reset-buffer ()
  (interactive)
  (unless buffer-file-name (user-error "Not a file buffer"))
  (when (yes-or-no-p "Discard all unstaged changes in this file? ")
    (unless (zerop (magit-call-git "restore" "--worktree" "--" buffer-file-name))
      (user-error "Git restore failed; buffer left unchanged"))
    (revert-buffer t t)))
(defun config-git-diff-head ()
  (interactive) (magit-diff-range "HEAD" nil (list buffer-file-name)))
(defun config-git-unstage-hunk ()
  "Select a staged hunk and press u to unstage it, including partial regions."
  (interactive) (magit-diff-staged nil nil (list buffer-file-name)))
(defun config-git-stage-hunk ()
  "Stage the current hunk, or open Magit for partial-hunk selection."
  (interactive)
  (if (use-region-p)
      (progn (magit-diff-unstaged nil (list buffer-file-name))
             (message "Select the desired diff lines and press s to stage"))
    (diff-hl-stage-current-hunk)))
(defun config-git-reset-hunk ()
  (interactive)
  (if (use-region-p)
      (progn (magit-diff-unstaged nil (list buffer-file-name))
             (message "Select the desired diff lines and press k to discard"))
    (diff-hl-revert-hunk)))
(evil-define-key 'normal 'global "]c" #'diff-hl-next-hunk "[c" #'diff-hl-previous-hunk)
(config-bind "g s" #'config-git-stage-hunk)
(config-bind "g r" #'config-git-reset-hunk)
(config-bind "g S" #'magit-file-stage)
(config-bind "g u" #'config-git-unstage-hunk)
(config-bind "g R" #'config-git-reset-buffer)
(config-bind "g p" #'diff-hl-show-hunk)
(config-bind "g b" #'magit-blame-addition)
(config-bind "g d" #'diff-hl-diff-goto-hunk)
(config-bind "g D" #'config-git-diff-head)
(config-bind "t b" #'blamer-mode)
(config-bind "t D" #'diff-hl-show-hunk)
