;;; tasks.el --- Compilation and project task selection -*- lexical-binding: t; -*-
(require 'compile)
(setq compilation-scroll-output 'first-error)
(defun config-run-task ()
  "Choose a package.json script, or enter a project compile command."
  (interactive)
  (let* ((default-directory (config-project-root))
         (package (expand-file-name "package.json" default-directory))
         (scripts (when (file-readable-p package)
                    (with-temp-buffer
                      (insert-file-contents package)
                      (map-keys (gethash "scripts" (json-parse-buffer))))))
         (task (when scripts (completing-read "Task: " (cons "Custom command" scripts) nil t))))
    (if (and task (not (equal task "Custom command")))
        (compile (concat "npm run " (shell-quote-argument task)))
      (call-interactively #'compile))))
(defun config-task-toggle ()
  (interactive)
  (if-let* ((window (get-buffer-window "*compilation*")))
      (quit-window nil window)
    (if-let* ((buffer (get-buffer "*compilation*")))
        (pop-to-buffer buffer)
      (user-error "No task yet; use SPC c c"))))
(config-bind "c c" #'config-run-task)
(config-bind "c C" #'config-task-toggle)
