;;; theme.el --- Shared Nix palettes and system appearance -*- lexical-binding: t; -*-
(deftheme config-dark "Shared dark palette.")
(deftheme config-light "Shared light palette.")
(dolist (entry `((config-dark . ,config-theme-dark) (config-light . ,config-theme-light)))
  (let* ((theme (car entry)) (colors (cdr entry))
         (bg (alist-get 'background colors)) (fg (alist-get 'foreground colors))
         (muted (alist-get 'muted colors)) (surface (alist-get 'hover colors)))
    (custom-theme-set-faces
     theme
     `(default ((t (:background ,bg :foreground ,fg))))
     `(cursor ((t (:background ,(alist-get 'accent colors)))))
     `(fringe ((t (:background ,bg))))
     `(region ((t (:background ,(alist-get 'selected colors)))))
     `(hl-line ((t (:background ,surface))))
     `(line-number ((t (:foreground ,muted :background ,bg))))
     `(line-number-current-line ((t (:foreground ,fg :background ,bg))))
     `(mode-line ((t (:background ,surface :foreground ,fg :box nil))))
     `(mode-line-inactive ((t (:background ,bg :foreground ,muted :box nil))))
     `(header-line ((t (:background ,bg :foreground ,muted :box nil))))
     `(minibuffer-prompt ((t (:foreground ,(alist-get 'accent colors) :weight bold))))
     `(font-lock-comment-face ((t (:foreground ,muted :slant italic))))
     `(font-lock-keyword-face ((t (:foreground ,(alist-get 'syntaxKeyword colors)))))
     `(font-lock-function-name-face ((t (:foreground ,(alist-get 'syntaxFunction colors)))))
     `(font-lock-string-face ((t (:foreground ,(alist-get 'syntaxString colors)))))
     `(font-lock-number-face ((t (:foreground ,(alist-get 'syntaxNumber colors)))))
     `(font-lock-type-face ((t (:foreground ,(alist-get 'syntaxType colors)))))
     `(font-lock-constant-face ((t (:foreground ,(alist-get 'accent2 colors)))))
     `(font-lock-variable-name-face ((t (:foreground ,fg))))
     `(link ((t (:foreground ,(alist-get 'link colors) :underline t))))
     `(error ((t (:foreground ,(alist-get 'error colors)))))
     `(warning ((t (:foreground ,(alist-get 'warning colors)))))
     `(success ((t (:foreground ,(alist-get 'success colors)))))
     `(diff-added ((t (:background ,(alist-get 'diffAddedBg colors)))))
     `(diff-removed ((t (:background ,(alist-get 'diffRemovedBg colors)))))
     `(diff-hl-insert ((t (:foreground ,(alist-get 'added colors) :background ,bg))))
     `(diff-hl-change ((t (:foreground ,(alist-get 'changed colors) :background ,bg))))
     `(diff-hl-delete ((t (:foreground ,(alist-get 'removed colors) :background ,bg))))
     `(vertico-current ((t (:background ,surface))))
     `(corfu-default ((t (:background ,surface :foreground ,fg))))
     `(corfu-current ((t (:background ,(alist-get 'selected colors)))))
     `(highlight-indent-guides-character-face ((t (:foreground ,(alist-get 'border colors))))))))
(set-face-attribute 'default nil :family config-font :height config-font-height)
(enable-theme 'config-dark)
(require 'auto-dark)
(setq auto-dark-themes '((config-dark) (config-light))
      auto-dark-allow-osascript t)
(unless noninteractive (auto-dark-mode 1))
(config-bind "t T" #'auto-dark-toggle-appearance)
